# Generated by Django 4.1.13 on 2024-02-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='Quantity_of_equipment')),
            ],
            options={
                'verbose_name': 'Category_Equipment',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Name_of_equipement')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('procurement', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='update_equipement')),
                ('created_on', models.DateField(auto_now=True, verbose_name='created_equipement')),
                ('state', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('classed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.category', verbose_name='Category_of_equipement')),
            ],
            options={
                'verbose_name': 'Equipment_stored',
            },
        ),
    ]
