# Generated by Django 5.0.3 on 2024-04-01 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='Quantity_of_equipment')),
                ('image', models.ImageField(blank=True, null=True, upload_to='enter_category/')),
            ],
            options={
                'verbose_name': 'Category_Equipment',
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now=True, verbose_name='created_equipement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialNumber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, verbose_name='Name_of_equipment')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('supplier', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='update_equipment')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='created_equipment')),
                ('state', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enter_equipment/')),
                ('classed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.category', verbose_name='Category_of_equipment')),
            ],
            options={
                'verbose_name': 'Equipment stored',
            },
        ),
        migrations.CreateModel(
            name='Equipment_Out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialNumber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, verbose_name='Name_of_equipment')),
                ('projet', models.CharField(max_length=100, verbose_name='Projet_of_equipment')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='update_equipment')),
                ('created_on', models.DateField(auto_now=True, verbose_name='created_equipment')),
                ('image', models.ImageField(blank=True, null=True, upload_to='enter_equipmentOut/')),
                ('classed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.category', verbose_name='Category_of_equipment')),
                ('equipment_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.equipment', verbose_name='equipment_in_stock')),
            ],
            options={
                'verbose_name': 'Equipment_Out',
            },
        ),
    ]
